# Numpy library

In [2]:
import numpy as np

1. Number of dimension

In [15]:
arr = np.array([[1,2,3,4,5], [4,5,6,7,8]])
print("number of dimensions: ", arr.ndim)

number of dimensions:  2


In [16]:
arr = np.array([1,2,3], ndmin = 2)
print("Define number of dimension when created: ", arr)

Define number of dimension when created:  [[1 2 3]]


2. Array indexing

In [31]:
arr = np.array([
                [
                    [1, 2, 3], 
                    [4, 5, 6]
                ], 
                [
                    [7, 8, 9], 
                    [10, 11, 12]
                ]
            ])
print("Number of dimensions: ", arr.ndim)
print("Number of First dimension -> number of second dimension -> last number : ",arr[0,1,-1])

Number of dimensions:  3
Number of First dimension -> number of second dimension -> last number  6


3. Array slicing
    * `[start:end:step]` : do not include end

In [37]:
print("Number of first dimension -> slice number from 0 to 1 dimension -> slice with step 2", arr[0, 0:2, ::2])

array([[1, 3],
       [4, 6]])

4. Data type
    * `i` - integer
    * `b` - boolean
    * `u` - unsigned integer
    * `f` - float
    * `c` - complex float
    * `m` - timedelta
    * `M` - datetime
    * `O` - object
    * `S` - string
    * `U` - unicode string
    * `V` - fixed chunk of memory for other type

In [39]:
arr = np.array([1,2,3,4])

print("Type of arr: ",type(arr))
print("Data type of arr: ",arr.dtype)

Type of arr:  <class 'numpy.ndarray'>
Data type of arr:  int32


In [44]:
# Creating arrays with a float data type
arr = np.array([1,2,3,4], dtype="f")
arr.dtype

dtype('float32')

In [46]:
# Converting data type on existing arr
intarr= arr.astype('i')
intarr.dtype

dtype('int32')

5. Array copy vs View

In [51]:
newarr = arr.copy()
newarr[0] = 1464
print(f"old arr : {arr} vs new arr : {newarr}")
print("newarr own it data? ", newarr.base)

old arr : [  1.   2.   3. 435.] vs new arr : [1464.    2.    3.  435.]
newarr own it data?  None


In [52]:
viewarr = arr.view()
viewarr[-1] = 435
print(f"old arr : {arr} vs view arr : {viewarr}")
print("view own it data? ", viewarr.base)

old arr : [  1.   2.   3. 435.] vs view arr : [  1.   2.   3. 435.]
view own it data?  [  1.   2.   3. 435.]


6. Array Shape

    The number of elements in each dimension

In [55]:
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("Shape of array: ", arr.shape)

Shape of array:  (2, 2, 2)


7. Array reshaping

    Return view **not copy**
    You can pass -1 so Numpy will calculate this number

In [61]:
arr = np.array([1,2,3,4,5,6,7,8])
twoDarr = arr.reshape(2,4)
print("2 rows with 4 columns", twoDarr)
threeDarr = arr.reshape(2,2,2)
print(threeDarr)

2 rows with 4 columns [[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


8. Array iterating

    `nditer()` deep iter: iterating on each scalar element
    
    `ndenumerate()`: return index type typle and value

In [69]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

for x in np.nditer(arr):
    print(x)
    
for idx, x in np.ndenumerate(arr):
    print(idx, x, sep=":")

1
2
3
4
5
6
7
8
(0, 0):1
(0, 1):2
(0, 2):3
(0, 3):4
(1, 0):5
(1, 1):6
(1, 2):7
(1, 3):8


9. Joining array

    Numpy join arrays. `concatenate()`, `stack()`, `hstack()`, `vstack()`, `dstack()`

In [106]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [107]:
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


`stack()` is same as concatenation, the only diference is that stacking is done along new asis

In [113]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

`hstack()` to stack along rows, `vstack()` to stack along column and `dstack()` to stack along height

In [119]:
harr = np.hstack((arr1, arr2))
print("Using hstack: ",harr)
varr = np.vstack((arr1, arr2))
print("Using vstack: ",varr)
darr = np.hstack((arr1, arr2))
print("Using dstack",darr)

Using hstack:  [1 2 3 4 5 6]
Using vstack:  [[1 2 3]
 [4 5 6]]
Using dstack [1 2 3 4 5 6]


10. Splitting numpy arrays

    `array_split()`, `hsplit`, `vsplit()`, `dsplit()`

In [108]:
# 1-D split
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 2)
newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [109]:
# 2D split
arr = np.array([[1, 2, 5, 6],
       [3, 4, 7, 8]])
newarr = (np.array_split(arr, 2, axis=1))
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [111]:
arr = np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

newarr = np.array_split(arr, 2, axis=0)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [122]:
# hsplit
arr = np.array([1, 2, 3, 4, 5, 6])
harr = np.hsplit(arr, 2)
harr

[array([1, 2, 3]), array([4, 5, 6])]

In [124]:
# vsplit
arr = np.array([[1, 2, 3],
 [4, 5, 6]])
harr = np.vsplit(arr, 2)
harr

[array([[1, 2, 3]]), array([[4, 5, 6]])]

11. Searching arrays

In [128]:
arr = np.array([1, 2, 3, 4, 5, 6])
# index of element 4
print("index of element 4", np.where(arr == 4))
# index of element mod 2 = 0
print("index of element mod 2 = 0", np.where(arr % 2 == 0))

index of element 4 (array([3], dtype=int64),)
index of element mod 2 = 0 (array([1, 3, 5], dtype=int64),)


In [129]:
# searchsorted() perform a binary search
print(np.searchsorted(arr, [2, 4, 6]))

[1 3 5]


12. Sorting array

In [131]:
arr = np.array([[4,1,5],[0,54,2]])
print(np.sort(arr))

[[ 1  4  5]
 [ 0  2 54]]


13. Filter array

In [134]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr > 3
newarr

array([False, False, False,  True,  True,  True])

14. Randon numbers

In [135]:
from numpy import random

In [156]:
# rand from 10 to 99 with size (2 rows,3 columns)
print(random.randint(10, 100, (2,3)))

[[14 94 45]
 [17 82 12]]


In [176]:
# random float between 0 and 1 with size (3 rows, 2 columns)
arr = random.rand(3, 2)

In [188]:
x = random.choice([3,55,2,1,4,], size=(3,2))
x

array([[4, 4],
       [1, 1],
       [3, 4]])

In [191]:
#random data with distributed
x = random.choice([1,2], p = [1, 0], size=10)
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [195]:
# shuffle mean change arrangement of element in-place
# permutation() mean random permuation of element of following array
arr = np.array([1,2,4])
random.shuffle(arr)
print(arr)

perarr = random.permutation(arr)
print(perarr)

[4 1 2]
[1 4 2]
